### ISSUE TITLE
Not an issue, but thanks, and good luck.

### ISSUE THREAD

**Issue by ghost** [Champ-Goblem/IntelWiFiDriver---Voodoo80211#1]
I've seen many attempts at this, and it appears that you are building on them (hopefully makes it easier/faster). I unfortunately am unable to offer anything other than encouragement (and testing hardware, I have a ac-8265 in my laptop, and would be willing to risk system stability to test this), but encourage you to continue work on this. Thanks, Good luck.

**Comment by Champ-Goblem** [comment]
Lets hope combining all the previous attempt ideas we can hopefully put something together. Thanks for the support it means a lot!
