### ISSUE TITLE
Not supported with 10.15

### ISSUE THREAD

**Issue by aestavan** [Champ-Goblem/IntelWiFiDriver---Voodoo80211#2]
after hitting command+B in Xcode I get an error saying that the build failed I then get an error in the  side of the screen saying "Validate Project Settings" and I personally don't wanna mess with that as last time I did with a diffrent project I had to rebuild my Hackintosh so if anyone could help me with this it would be greatly appreciated.

**Comment by Champ-Goblem** [comment]
Please don't run this yet as its not ready
