### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by johnnynunez** [Champ-Goblem/IntelWiFiDriver---Voodoo80211#4]
You may be interested in helping in this repository
https://github.com/zxystd/AppleIntelWifiAdapter/tree/feature-rewrite-all

**Comment by simmy1232** [comment]
@johnnync13 is that repo's wifi working now?

**Comment by Champ-Goblem** [comment]
By the looks of it that repos on about the same amount of progress as this one is, just in a different areas, but seems like they are taking a similar idea. I might drop them a message once exams are over

**Comment by johnnynunez** [comment]
@Champ-Goblem you should know this...
http://bbs.pcbeta.com/viewthread-1838489-1-1.html

**Comment by Champ-Goblem** [comment]
Oh damn, so its definitely possible then, thank you for linking me to this.
