### ISSUE TITLE
macos catalina failed to load kext

### ISSUE THREAD

**Issue by ghost** [Champ-Goblem/IntelWiFiDriver---Voodoo80211#5]
macOS: Catalina 10.15.3 (19D76)
Bootloader: Clover r4988
WL/BT Card: Intel Wireless-AC 9260

built extension using xCode 9.4.1, succeded

copied kext to /tmp, chown to root:wheel

kextload -v 6 /tmp/net80211.kext
outputs:

Kext user-space log filter changed from 0xff2 to 0xfff.
Kext kernel-space log filter changed from 0xff2 to 0xfff.
Requesting load of /tmp/net80211.kext.
/tmp/net80211.kext failed to load - (libkern/kext) dependency load failed; check the system/kernel logs for errors or try kextutil(8).

console output:

![Screenshot 2020-02-01 at 22 53 18](https://user-images.githubusercontent.com/60554672/73599711-b5e60780-4546-11ea-99a8-5c68b4bc385c.png)

I know that it's not in a working state rn, just letting u know

**Comment by Champ-Goblem** [comment]
I think thats because im running older headers at the moment, ill update them at some point, but thanks for that!

**Comment by kprinssu** [comment]
@Champ-Goblem sorry to chime, not exactly my place or time, but I suggest using Lilu to dynamically find and hook into the specific functions.

**Comment by Champ-Goblem** [comment]
@kprinssu Im not entirely sure what lilu is, I think I understand the concept but I dont think it would really apply here? I would of thought using the headers were a better option because im not trying to dynamically patch any part of xnu, im just simply trying to interface to the rest of network handling functions in xnu.
Although if using lilu would make my job easier of working out what each function does thats imported from IO80211Controller then by all means please let me know xD

**Comment by kprinssu** [comment]
@Champ-Goblem Ideally, we can use virtual tables to find and hook the proper functions, which Lilu would be perfect to use for in this case. The only thing you will need is have the necessary structs (which the existing headers should provide).

I'll try to find an example that you can use.

**Comment by Champ-Goblem** [comment]
@kprinssu whats the difference between that and the dynamic linking the kext loader does upon kext load. I'm not entirely sure why I would want to use lilu over that?

**Comment by rv32ima** [comment]
@Champ-Goblem speaking of which, my repo (hatf0/Black80211-Catalina) has the most up-to-date headers if needed (except for IO80211Interface, i'll get to that eventually)

**Comment by kprinssu** [comment]
@Champ-Goblem you're right. I hadn't spent the time looking into how the actual binaries were being linked. Considering it would take more time and effort to implement the Lilu approach.

**Comment by Champ-Goblem** [comment]
@kprinssu thank you for trying to help though, I appreciate having other people's views of the situation, it can lead to some refreshing ideas
