### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by lgariv** [Champ-Goblem/IntelWiFiDriver---Voodoo80211#6]
First of all, thank you for the effort you're putting into that! that's really great, wish you good luck! Also, if you need to do some testing, I have a second installation for testing such things - so I have no problem screwing things up at all haha! You can also contact me on Twitter @LGarivOfficial or Discord at LGariv#0290 .

**Comment by Champ-Goblem** [comment]
Many thanks for the offer, do you have any experience with debugging kexts as I will be looking for people with relevant experience in that first?

**Comment by averycblack** [comment]
I'd be interested in helping out testing as well - I've done some work with my own fork of VoodooPS2 for my M4700 and a little work with WhateverGreen to get backlight working on the M4700 as well (That stupid laptop, lol), though that's the extent of my experience. I do dig around source code quite a bit though.
I'd be testing on an X1 Extreme with an Intel 9560 wifi chip
Discord: 1Revenger1#2952

**Comment by Champ-Goblem** [comment]
Thats the kind of experience I would be looking for, for the first round of testers so thank you!
