### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by imperaughier** [Champ-Goblem/IntelWiFiDriver---Voodoo80211#8]
Hi! is the development of this driver dead? There is also a development other than that of the issue ( #7 ). You might wanna look at this dev: https://github.com/AppleIntelWifi/adapter

They're looking also for community help in the development

**Comment by Champ-Goblem** [comment]
No not yet, Ive been quite busy recently but ive got some local commits to push, but as im working on my mac os install with no wifi I cant push till I connect over ethernet. Im definitely open to helping out, when ive got more time ill contact that repo owner and see if I can be of service, thanks for the information!
